package com.liulang.dao;

import com.liulang.model.CommodityOrder;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("commodityOrderMapper")
public interface CommodityOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_order
     *
     * @mbggenerated Mon Jun 29 20:37:39 CST 2020
     */
    int deleteByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_order
     *
     * @mbggenerated Mon Jun 29 20:37:39 CST 2020
     */
    int insert(CommodityOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_order
     *
     * @mbggenerated Mon Jun 29 20:37:39 CST 2020
     */
    CommodityOrder selectByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_order
     *
     * @mbggenerated Mon Jun 29 20:37:39 CST 2020
     */
    List<CommodityOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_order
     *
     * @mbggenerated Mon Jun 29 20:37:39 CST 2020
     */
    int updateByPrimaryKey(CommodityOrder record);

    CommodityOrder selectByOpenid(String openid);
}