package com.liulang.dao;

import com.liulang.model.Course;
import java.util.List;

public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_goods
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    int deleteByPrimaryKey(Integer courseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_goods
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    int insert(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_goods
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    Course selectByPrimaryKey(Integer courseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_goods
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    List<Course> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_goods
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    int updateByPrimaryKey(Course record);
}