package com.liulang.dao;

import com.liulang.model.CourseSubitem;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("courseSubitemMapper")
public interface CourseSubitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_subitem_goods
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    int deleteByPrimaryKey(Integer courseSubId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_subitem_goods
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    int insert(CourseSubitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_subitem_goods
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    CourseSubitem selectByPrimaryKey(Integer courseSubId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_subitem_goods
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    List<CourseSubitem> selectAll();

    List<CourseSubitem> selectByCourseid(Integer courseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_subitem_goods
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    int updateByPrimaryKey(CourseSubitem record);
}