package com.liulang.dao;

import com.liulang.model.User;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("userMapper")
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechart_user
     *
     * @mbggenerated Wed Jul 01 10:35:04 CST 2020
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechart_user
     *
     * @mbggenerated Wed Jul 01 10:35:04 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechart_user
     *
     * @mbggenerated Wed Jul 01 10:35:04 CST 2020
     */
    User selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechart_user
     *
     * @mbggenerated Wed Jul 01 10:35:04 CST 2020
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wechart_user
     *
     * @mbggenerated Wed Jul 01 10:35:04 CST 2020
     */
    int updateByPrimaryKey(User record);

    Integer selectByOpenid(String openid);
}