package com.liulang.model;

public class CourseSubitem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_subitem_goods.course_sub_id
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    private Integer courseSubId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_subitem_goods.courseid
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_subitem_goods.seq
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_subitem_goods.subitem
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    private String subitem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_subitem_goods.subitem_title
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    private String subitemTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_subitem_goods.video_url
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    private String videoUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_subitem_goods.course_sub_id
     *
     * @return the value of course_subitem_goods.course_sub_id
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public Integer getCourseSubId() {
        return courseSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_subitem_goods.course_sub_id
     *
     * @param courseSubId the value for course_subitem_goods.course_sub_id
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public void setCourseSubId(Integer courseSubId) {
        this.courseSubId = courseSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_subitem_goods.courseid
     *
     * @return the value of course_subitem_goods.courseid
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_subitem_goods.courseid
     *
     * @param courseid the value for course_subitem_goods.courseid
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_subitem_goods.seq
     *
     * @return the value of course_subitem_goods.seq
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_subitem_goods.seq
     *
     * @param seq the value for course_subitem_goods.seq
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_subitem_goods.subitem
     *
     * @return the value of course_subitem_goods.subitem
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public String getSubitem() {
        return subitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_subitem_goods.subitem
     *
     * @param subitem the value for course_subitem_goods.subitem
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public void setSubitem(String subitem) {
        this.subitem = subitem == null ? null : subitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_subitem_goods.subitem_title
     *
     * @return the value of course_subitem_goods.subitem_title
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public String getSubitemTitle() {
        return subitemTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_subitem_goods.subitem_title
     *
     * @param subitemTitle the value for course_subitem_goods.subitem_title
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public void setSubitemTitle(String subitemTitle) {
        this.subitemTitle = subitemTitle == null ? null : subitemTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_subitem_goods.video_url
     *
     * @return the value of course_subitem_goods.video_url
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_subitem_goods.video_url
     *
     * @param videoUrl the value for course_subitem_goods.video_url
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    @Override
    public String toString() {
        return "CourseSubitem{" +
                "courseSubId=" + courseSubId +
                ", courseid=" + courseid +
                ", seq=" + seq +
                ", subitem='" + subitem + '\'' +
                ", subitemTitle='" + subitemTitle + '\'' +
                ", videoUrl='" + videoUrl + '\'' +
                '}';
    }
}