package com.liulang.model;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_goods.courseid
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_goods.seq
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_goods.description
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_goods.url
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_goods.detailed
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    private String detailed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_goods.courseid
     *
     * @return the value of course_goods.courseid
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_goods.courseid
     *
     * @param courseid the value for course_goods.courseid
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_goods.seq
     *
     * @return the value of course_goods.seq
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_goods.seq
     *
     * @param seq the value for course_goods.seq
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_goods.description
     *
     * @return the value of course_goods.description
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_goods.description
     *
     * @param description the value for course_goods.description
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_goods.url
     *
     * @return the value of course_goods.url
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_goods.url
     *
     * @param url the value for course_goods.url
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_goods.detailed
     *
     * @return the value of course_goods.detailed
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public String getDetailed() {
        return detailed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_goods.detailed
     *
     * @param detailed the value for course_goods.detailed
     *
     * @mbggenerated Sun Jun 14 17:40:10 CST 2020
     */
    public void setDetailed(String detailed) {
        this.detailed = detailed == null ? null : detailed.trim();
    }
}